var annotated_dup =
[
    [ "geogebra", "d6/d4a/namespacegeogebra.html", [
      [ "AlreadyExistsError", "d9/d19/classgeogebra_1_1AlreadyExistsError.html", null ],
      [ "Geogebra", "dc/df0/classgeogebra_1_1Geogebra.html", "dc/df0/classgeogebra_1_1Geogebra" ],
      [ "LabelAlreadyUse", "d3/de3/classgeogebra_1_1LabelAlreadyUse.html", null ]
    ] ],
    [ "MyLibrary", null, [
      [ "Example", "d7/d8e/classMyLibrary_1_1Example.html", "d7/d8e/classMyLibrary_1_1Example" ],
      [ "SecondExample", "dd/dc4/classMyLibrary_1_1SecondExample.html", null ],
      [ "SubclassExample", "db/d5b/classMyLibrary_1_1SubclassExample.html", "db/d5b/classMyLibrary_1_1SubclassExample" ]
    ] ],
    [ "AbstractAbsoluteEncoder", "d4/ddc/classAbstractAbsoluteEncoder.html", "d4/ddc/classAbstractAbsoluteEncoder" ],
    [ "AbstractCodewheel", "d1/d6f/classAbstractCodewheel.html", "d1/d6f/classAbstractCodewheel" ],
    [ "AbstractDriver", "d4/de2/classAbstractDriver.html", "d4/de2/classAbstractDriver" ],
    [ "AbstractMotor", "d2/d61/classAbstractMotor.html", "d2/d61/classAbstractMotor" ],
    [ "AbstractMoveStrategy", "de/dc0/classAbstractMoveStrategy.html", "de/dc0/classAbstractMoveStrategy" ],
    [ "AX12", "d8/d27/classAX12.html", "d8/d27/classAX12" ],
    [ "BasicMoveStrategy", "de/d22/classBasicMoveStrategy.html", "de/d22/classBasicMoveStrategy" ],
    [ "BasicTurnStrategy", "db/d2b/classBasicTurnStrategy.html", "db/d2b/classBasicTurnStrategy" ],
    [ "Block_header", "dc/da5/unionBlock__header.html", null ],
    [ "BournsACEncoder", "d0/d04/classBournsACEncoder.html", "d0/d04/classBournsACEncoder" ],
    [ "BrushlessMotor", "d7/d82/classBrushlessMotor.html", "d7/d82/classBrushlessMotor" ],
    [ "Buttons", "dc/d2e/classButtons.html", null ],
    [ "Clock", "df/d45/classClock.html", "df/d45/classClock" ],
    [ "Codewheel", "dd/df3/classCodewheel.html", "dd/df3/classCodewheel" ],
    [ "Color", "d0/da2/structColor.html", null ],
    [ "CRC16", "db/d6d/classCRC16.html", null ],
    [ "Cube", "df/dd5/classCube.html", "df/dd5/classCube" ],
    [ "DCMotor", "dd/d4c/classDCMotor.html", "dd/d4c/classDCMotor" ],
    [ "DCMotorsDriver", "d8/de4/classDCMotorsDriver.html", "d8/de4/classDCMotorsDriver" ],
    [ "Decisions", "d9/da9/classDecisions.html", null ],
    [ "DifferentialController", "d5/d9e/classDifferentialController.html", "d5/d9e/classDifferentialController" ],
    [ "DynamixelClass", "df/dc5/classDynamixelClass.html", null ],
    [ "Elevator", "d9/db0/classElevator.html", "d9/db0/classElevator" ],
    [ "EndStop", "df/d5b/classEndStop.html", "df/d5b/classEndStop" ],
    [ "FullSpeedServo", "d9/df7/classFullSpeedServo.html", "d9/df7/classFullSpeedServo" ],
    [ "LedButton", "d8/d45/classLedButton.html", null ],
    [ "limites_actionneurs", "de/d35/structlimites__actionneurs.html", null ],
    [ "Logger", "db/d67/classLogger.html", null ],
    [ "Musique", "d6/da1/classMusique.html", "d6/da1/classMusique" ],
    [ "NonCopyable", "dc/d3c/classNonCopyable.html", null ],
    [ "ObjectDetector", "d6/dd4/classObjectDetector.html", "d6/dd4/classObjectDetector" ],
    [ "Odometry", "d6/dc3/classOdometry.html", "d6/dc3/classOdometry" ],
    [ "PeriodicProcess", "d2/dfa/classPeriodicProcess.html", "d2/dfa/classPeriodicProcess" ],
    [ "PID", "d8/da9/classPID.html", "d8/da9/classPID" ],
    [ "Point", "d8/d43/structPoint.html", null ],
    [ "Position", "d0/df4/structPosition.html", "d0/df4/structPosition" ],
    [ "PositionController", "d2/d64/classPositionController.html", "d2/d64/classPositionController" ],
    [ "PurePursuit", "de/d96/classPurePursuit.html", "de/d96/classPurePursuit" ],
    [ "SensorArray", "de/d4b/classSensorArray.html", "de/d4b/classSensorArray" ],
    [ "ShiftRegister", "de/ded/classShiftRegister.html", null ],
    [ "Sphere", "de/d9d/classSphere.html", "de/d9d/classSphere" ],
    [ "StepByStepMotor", "d9/dd4/classStepByStepMotor.html", null ],
    [ "Tache", "d0/d85/classTache.html", null ],
    [ "TacheBanderole", "dd/ddc/classTacheBanderole.html", null ],
    [ "TacheDescendreReculer", "d9/d1e/classTacheDescendreReculer.html", null ],
    [ "TacheEmpiler", "d0/dda/classTacheEmpiler.html", null ],
    [ "TacheExe", "de/d8f/classTacheExe.html", null ],
    [ "TacheGoto", "dd/d5e/classTacheGoto.html", null ],
    [ "TacheGotoWaypoints", "dc/dd3/classTacheGotoWaypoints.html", null ],
    [ "TacheGotoWithFunct", "db/dc7/classTacheGotoWithFunct.html", null ],
    [ "TacheMoveDelta", "d3/de7/classTacheMoveDelta.html", null ],
    [ "TacheSTOP", "d1/d5c/classTacheSTOP.html", null ],
    [ "TacheSwitch", "d0/db3/classTacheSwitch.html", null ],
    [ "TacheTransport", "d8/d9f/classTacheTransport.html", null ],
    [ "TacheTurnOnTheSpot", "d8/d8a/classTacheTurnOnTheSpot.html", null ],
    [ "TacheWait", "d3/d62/classTacheWait.html", null ],
    [ "Teleplot", "d8/d4b/classTeleplot.html", "d8/d4b/classTeleplot" ],
    [ "TurnOnTheSpot", "d9/dee/classTurnOnTheSpot.html", "d9/dee/classTurnOnTheSpot" ],
    [ "VelocityController", "de/d33/classVelocityController.html", "de/d33/classVelocityController" ],
    [ "VL53L5CX", "d9/d0e/classVL53L5CX.html", "d9/d0e/classVL53L5CX" ],
    [ "VL53L5CX_Configuration", "da/dce/structVL53L5CX__Configuration.html", null ],
    [ "VL53L5CX_Platform", "de/d5c/structVL53L5CX__Platform.html", null ],
    [ "VL53L5CX_ResultsData", "d4/d7d/structVL53L5CX__ResultsData.html", null ],
    [ "WBConstants", "d9/d49/structWBConstants.html", null ]
];