var searchData=
[
  ['vcoroutineschedule_0',['vCoRoutineSchedule',['../da/d5f/group__vCoRoutineSchedule.html',1,'']]],
  ['vqueuedelete_1',['vQueueDelete',['../de/d60/group__vQueueDelete.html',1,'']]],
  ['vsemaphorecreatebinary_2',['vSemaphoreCreateBinary',['../da/d7c/group__vSemaphoreCreateBinary.html',1,'']]],
  ['vsemaphoredelete_3',['vSemaphoreDelete',['../da/d45/group__vSemaphoreDelete.html',1,'']]],
  ['vstreambufferdelete_4',['vStreamBufferDelete',['../dc/d37/group__vStreamBufferDelete.html',1,'']]],
  ['vtaskdelay_5',['vTaskDelay',['../d6/de9/group__vTaskDelay.html',1,'']]],
  ['vtaskdelayuntil_6',['vTaskDelayUntil',['../d7/d86/group__vTaskDelayUntil.html',1,'']]],
  ['vtaskdelete_7',['vTaskDelete',['../d5/dae/group__vTaskDelete.html',1,'']]],
  ['vtaskendscheduler_8',['vTaskEndScheduler',['../da/db4/group__vTaskEndScheduler.html',1,'']]],
  ['vtaskgetinfo_9',['vTaskGetInfo',['../dd/d43/group__vTaskGetInfo.html',1,'']]],
  ['vtaskgetruntimestats_10',['vTaskGetRunTimeStats',['../d3/dbd/group__vTaskGetRunTimeStats.html',1,'']]],
  ['vtasklist_11',['vTaskList',['../df/d1b/group__vTaskList.html',1,'']]],
  ['vtaskpriorityset_12',['vTaskPrioritySet',['../de/d5a/group__vTaskPrioritySet.html',1,'']]],
  ['vtaskresume_13',['vTaskResume',['../db/da4/group__vTaskResume.html',1,'']]],
  ['vtaskresumefromisr_14',['vTaskResumeFromISR',['../d6/ddf/group__vTaskResumeFromISR.html',1,'']]],
  ['vtasksettimeoutstate_15',['vTaskSetTimeOutState',['../d2/d56/group__vTaskSetTimeOutState.html',1,'']]],
  ['vtaskstartscheduler_16',['vTaskStartScheduler',['../da/d9b/group__vTaskStartScheduler.html',1,'']]],
  ['vtasksuspend_17',['vTaskSuspend',['../d1/dd4/group__vTaskSuspend.html',1,'']]],
  ['vtasksuspendall_18',['vTaskSuspendAll',['../d3/d3e/group__vTaskSuspendAll.html',1,'']]]
];
