//
// Created by awing on 11/05/2026.
//

#ifndef GRAFCET_CONFIG_H
#define GRAFCET_CONFIG_H

#ifndef GRAFCET_MAX_NODE_PARENTS
#define GRAFCET_MAX_NODE_PARENTS 10
#endif

#ifndef GRAFCET_MAX_NODE_CHILDREN
#define GRAFCET_MAX_NODE_CHILDREN 10
#endif

#ifndef GRAFCET_MAX_QUEUE_SIZE
#define GRAFCET_MAX_QUEUE_SIZE 10
#endif

#endif // GRAFCET_CONFIG_H

