name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Generate GitHub App Token
          id: generate-token
          uses: actions/create-github-app-token@v3
          with:
            client-id: ${{ secrets.APP_CLIENT_ID }}
            private-key: ${{ secrets.APP_PRIVATE_KEY }}
  
        - name: Setup SSH
          env:
            GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf git@github.com:
            
        - uses: actions/checkout@v6
          with:
            submodules: recursive
            token: ${{ steps.generate-token.outputs.token }}
        # You may pin to the exact commit or the version.
        # uses: langroodi/doxygenize@7678ae6c3ab3dd9c039a1f814c9bb00ecc17cc17
        - uses: langroodi/doxygenize@v1.7.1
          with:
          # Doxygen configuration file path
            doxygenconf: ./doc/Doxyfile # default is ./Doxyfile
          # Generated HTML documents output folder
            htmloutput: ./html
                
